services:
  server:
    build:
      context: .
      target: tatc_server
    ports:
      - "8000:8000"
    links:
      - worker
      - broker
      - backend
    environment:
      TATC_BROKER: amqp://guest:guest@broker:5672//
      TATC_BACKEND: redis://backend:6379/
      TATC_CESIUM_TOKEN: ${TATC_CESIUM_TOKEN}
      TATC_DATABASE_URL: sqlite+aiosqlite:///data/data.db
    volumes:
      - tatc-data:/var/tatc-app/data
  worker:
    build:
      context: .
      target: tatc_worker
    links:
      - broker
      - backend
    environment:
      TATC_BROKER: amqp://guest:guest@broker:5672//
      TATC_BACKEND: redis://backend:6379/
  broker:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
  backend:
    image: redis:6
    ports:
      - "6379:6379"
volumes:
  tatc-data:
