name: Docker Image Build CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Build and push the server Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        target: tatc_server
    
    - name: Build and push the worker Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        target: tatc_worker